apiVersion: v1
kind: Service
metadata:
  name: kafka-producer
  namespace: kafka
  labels:
    app: kafka-producer
    component: producer
spec:
  type: ClusterIP
  selector:
    app: kafka-producer
  ports:
    - name: http
      port: 8888
      targetPort: 8888
      protocol: TCP
